DB_URL='postgres://postgres:1111@localhost:5433/gollang?sslmode=disable'
run:
	go run cmd/main.go
mod:
	go mod init api_getaway_service
	go mod tidy
	go mod vendor
tidy:
	go mod tidy
	go mod vendor




